# syntax=docker/dockerfile:labs
ARG CPU_THREADS=8
ARG KERNEL_VERSION
ARG GLIBC_VERSION
FROM cppdevenv-binutils-git AS binutils
ARG CPU_THREADS
ARG KERNEL_VERSION
ARG GLIBC_VERSION

RUN mkdir -p /opt/gcc-git-linux-aarch64

RUN mkdir -p /binutils-build-aarch64

WORKDIR /binutils-build-aarch64

RUN /binutils-gdb-git/configure \
    --prefix=/opt/gcc-git-linux-aarch64 \
    --target=aarch64-linux \
    --disable-multilib

RUN make -j${CPU_THREADS}
RUN make install

WORKDIR /

# TODO: fetch kernel src install headers

FROM cppdevenv-gcc-git-update AS gcc
ARG CPU_THREADS
COPY --from=binutils /opt/gcc-git-linux-aarch64 /opt/gcc-git-linux-aarch64

# build cross-compilers
RUN mkdir -p /gcc-build-aarch64
WORKDIR /gcc-build-aarch64

RUN /gcc-source/configure \
    --prefix=/opt/gcc-git-linux-aarch64 \
    --target=aarch64-linux \
    --enable-languages=c,c++ \
    --disable-multilib \
    --enable-lto

RUN make -j${CPU_THREADS} all-gcc
RUN make install-gcc

WORKDIR /
