# syntax=docker/dockerfile:labs
FROM gccbld AS gcc-build
FROM baseimg AS base
COPY --from=gcc-build /opt/gcc-git /opt/gcc-git

# install runtime deps for gcc
RUN DEBIAN_FRONTEND=noninteractive \
    apt-get install --yes \
    libgmp10 \
    libmpfr6 \
    libmpc3 \
    libisl23 \
    libzstd1 \
    # TODO: should we compile binutils from source???
    binutils
