# syntax=docker/dockerfile:labs
FROM baseimg

# dependencies for binutils
RUN DEBIAN_FRONTEND=noninteractive \
    apt-get install --yes \
        g++ make gawk

# clone binutils source code
RUN git clone --branch master --single-branch  \
    git://sourceware.org/git/binutils-gdb.git /binutils-gdb-source

