# syntax=docker/dockerfile:labs
FROM baseimg

# dependencies for gcc
RUN DEBIAN_FRONTEND=noninteractive \
    apt-get install --yes \
        m4 flex bison build-essential file make g++ \
        libgmp-dev \
        libmpfr-dev \
        libmpc-dev \
        libisl-dev \
        libzstd-dev

# clone gcc source code
RUN git clone --branch master --single-branch git://gcc.gnu.org/git/gcc.git /gcc-source

